#!/bin/bash
#THIS WILL DELETE ALL DICOM FILES IN ANY DIRECTORIES DOWNSTREAM OF WHERE IT IS RUN
#USE WITH EXTREME CAUTION AFTER YOU HAVE DETERMINED THAT YOU NO LONGER NEED YOUR DICOMS
find . -type f -name "*.dcm" -delete
